const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2023 - Present",
    title: "Bachelor's Degree in Computer Science",
    desc: "University of Minnesota — Pursuing a B.S. in Computer Science with a Mathematics minor. Dean's List Fall 2023, Spring 2024.",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - 2023",
    title: "Associate of Arts Degree",
    desc: "Normandale Community College — Completed an Associate degree while in high school.",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2019 - 2021",
    title: "High School Diploma",
    desc: "Graduated high school while concurrently earning college credits through PSEO.",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "2024 - Present",
    title: "Drone Simulation Project",
    desc: "Developing a campus drone simulation in C++ focused on flight path optimization, real-time monitoring, and emergency protocols.",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2024",
    title: "AWS Data Engineering Capstone",
    desc: "Built scalable AWS pipelines with S3, Glue, Lambda, and Athena to process large datasets efficiently.",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "May 2024 - June 2024",
    title: "Section Leader | Stanford",
    desc: "Taught Stanford’s CS106A (Python) to 1600+ students globally, provided personalized feedback, and mentored beginners in coding.",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "2024 - Present",
    title: "Management Leadership for Tomorrow (MLT) Fellow",
    desc: "Selected for an 18-month leadership program preparing high-achieving diverse talent for top tech roles.",
  },
  {
    id: 8,
    category: "experience",
    icon: "icon-briefcase",
    year: "2024 - Present",
    title: "ColorStack Member",
    desc: "Active member of ColorStack, a nonprofit supporting Black and Latinx students in Computer Science through community and career development.",
  },
];

export default Data;